kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: iota-cli
  namespace: default
  labels: 
    app: iota-cli-dt
spec: 
  template: 
    metadata: 
      labels: 
        app: iota-cli-dt
    spec: 
      containers: 
      - name: iota-cli-dt
        image: iota-cli:v1
        imagePullPolicy: IfNotPresent
        ports: 
        - containerPort: 5000
          name: iotacliport
        env: 
        - name: ENABLE_BATCHING
          value: 'true'
        - name: HOST_IP
          value: '10.105.229.214:14700'
---
apiVersion: v1
kind: Service
metadata: 
   name: iota-cli-dt
   namespace: default
spec:
  type: NodePort
  selector: 
    app: iota-cli-dt
  ports: 
  - name: iotacliserverport
    port: 5000
    targetPort: iotacliport
